# Generated by Django 4.2.7 on 2025-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_size_remove_category_attributes_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.size'),
        ),
    ]
