# Generated by Django 5.2.6 on 2025-09-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='measurement_unit',
            field=models.CharField(blank=True, choices=[('meter', 'Mètre'), ('cm', 'Centimètre'), ('yard', 'Yard'), ('piece', 'Pièce')], default='meter', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='size_type',
            field=models.CharField(choices=[('standard', 'Taille standard'), ('measurement', 'Mesure')], default='standard', max_length=20),
        ),
    ]
