# Generated by Django 5.2.6 on 2025-09-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
