# Generated by Django 6.0 on 2025-12-04 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_notes_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Image de produit', 'verbose_name_plural': 'Images de produits'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('upload', 'Fichier uploadé'), ('youtube', 'Lien YouTube'), ('vimeo', 'Lien Vimeo'), ('url', 'URL externe')], default='upload', max_length=20)),
                ('video_file', models.FileField(blank=True, help_text='Fichier vidéo (MP4, WebM, etc.)', null=True, upload_to='products/videos/')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube, Vimeo ou autre', null=True)),
                ('title', models.CharField(blank=True, help_text='Titre de la vidéo', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description de la vidéo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniature de la vidéo', null=True, upload_to='products/video_thumbnails/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='shop.product')),
            ],
            options={
                'verbose_name': 'Vidéo de produit',
                'verbose_name_plural': 'Vidéos de produits',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
